### ISSUE TITLE
git-lint run only on staged files 

### ISSUE THREAD

**Issue by saurabhprakash** [sk-/git-lint#103]
Current git-lint has following options

Options:
    -h             Show the usage patterns.
    --version      Prints the version number.
    -f --force     Shows all the lines with problems.
    -t --tracked   Lints only tracked files.
    --json         Prints the result as a json string. Useful to use it in
                   conjunction with other tools.
    --last-commit  Checks the last checked-out commit. This is mostly useful
                   when used as: git checkout <revid>; git lint --last-commit.

Do we have any option to run only only on staged files(for commit)?

**Comment by sk-** [comment]
There's no such option at the moment as I haven't needed it before. PRs are welcomed.
