### ISSUE TITLE
'ascii' codec can't decode byte 0xc3

### ISSUE THREAD

**Issue by Dawars** [sk-/git-lint#107]
I can't install this through pip, getting the following error:
Using Debian 64 bit in virtualbox on a mac with Python 3.4.2
```
pip install git-lint
Collecting git-lint
  Using cached git-lint-0.0.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jm4spkm7/git-lint/setup.py", line 29, in <module>
        long_description=open('README.rst').read(),
      File "/home/vagrant/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8309: ordinal not in range(128)

    ----------------------------------------
```

**Comment by Dawars** [comment]
This occurs during the vagrant installation of mangaki: https://github.com/mangaki/mangaki
The error might be there, I'm not sure

`TASK [mangaki_source : Ensure debug-mode dependencies are installed.] **********
fatal: [default]: FAILED! => {"changed": false, "cmd": "/home/vagrant/venv/bin/pip install -r /vagrant/mangaki//../requirements/dev.txt", "msg": "stdout: Collecting Django==1.11.* (from -r /vagrant/mangaki//../requirements/./production.txt (line 1))\n  Downloading Django-1.11.10-py2.py3-none-any.whl (6.9MB)\nCollecting django-allauth==0.28 (from -r /vagrant/mangaki//../requirements/./production.txt (line 2))\n  Downloading django-allauth-0.28.0.tar.gz (439kB)\nCollecting markdown (from -r /vagrant/mangaki//../requirements/./production.txt (line 3))\n  Downloading Markdown-2.6.11-py2.py3-none-any.whl (78kB)\nCollecting django-bootstrap3==8.2.* (from -r /vagrant/mangaki//../requirements/./production.txt (line 4))\n  Downloading django-bootstrap3-8.2.3.tar.gz\nCollecting psycopg2 (from -r /vagrant/mangaki//../requirements/./production.txt (line 5))\n  Downloading psycopg2-2.7.4-cp34-cp34m-manylinux1_x86_64.whl (2.7MB)\nCollecting numpy>=1.13 (from -r /vagrant/mangaki//../requirements/./production.txt (line 6))\n  Downloading numpy-1.14.1-cp34-cp34m-manylinux1_x86_64.whl (12.1MB)\nCollecting beautifulsoup4 (from -r /vagrant/mangaki//../requirements/./production.txt (line 7))\n  Downloading beautifulsoup4-4.6.0-py3-none-any.whl (86kB)\nCollecting natsort (from -r /vagrant/mangaki//../requirements/./production.txt (line 8))\n  Downloading natsort-5.2.0-py2.py3-none-any.whl\nCollecting django-analytical (from -r /vagrant/mangaki//../requirements/./production.txt (line 9))\n  Downloading django_analytical-2.4.0-py3-none-any.whl (71kB)\nCollecting django-cookie-law (from -r /vagrant/mangaki//../requirements/./production.txt (line 10))\n  Downloading django-cookie-law-1.0.13.tar.gz\nCollecting django-js-reverse (from -r /vagrant/mangaki//../requirements/./production.txt (line 11))\n  Downloading django_js_reverse-0.8.1-py2.py3-none-any.whl\nCollecting scikit-learn==0.18.* (from -r /vagrant/mangaki//../requirements/./production.txt (line 12))\n  Downloading scikit_learn-0.18.2-cp34-cp34m-manylinux1_x86_64.whl (11.9MB)\nCollecting Cython (from -r /vagrant/mangaki//../requirements/./production.txt (line 13))\n  Downloading Cython-0.27.3-cp34-cp34m-manylinux1_x86_64.whl (3.0MB)\nCollecting scipy>=0.19.1 (from -r /vagrant/mangaki//../requirements/./production.txt (line 14))\n  Downloading scipy-1.0.0-cp34-cp34m-manylinux1_x86_64.whl (47.6MB)\nCollecting pandas (from -r /vagrant/mangaki//../requirements/./production.txt (line 15))\n  Downloading pandas-0.22.0.tar.gz (11.3MB)\nCollecting responses==0.5.1 (from -r /vagrant/mangaki//../requirements/./production.txt (line 16))\n  Downloading responses-0.5.1-py2.py3-none-any.whl\nCollecting jinja2 (from -r /vagrant/mangaki//../requirements/./production.txt (line 17))\n  Downloading Jinja2-2.10-py2.py3-none-any.whl (126kB)\nCollecting lxml==3.6.* (from -r /vagrant/mangaki//../requirements/./production.txt (line 18))\n  Downloading lxml-3.6.4-cp34-cp34m-manylinux1_x86_64.whl (4.2MB)\nCollecting raven==6.1.* (from -r /vagrant/mangaki//../requirements/./production.txt (line 19))\n  Downloading raven-6.1.0-py2.py3-none-any.whl (279kB)\nCollecting djangorestframework==3.6.* (from -r /vagrant/mangaki//../requirements/./production.txt (line 20))\n  Downloading djangorestframework-3.6.4-py2.py3-none-any.whl (1.5MB)\nCollecting coreapi==2.3.* (from -r /vagrant/mangaki//../requirements/./production.txt (line 21))\n  Downloading coreapi-2.3.3-py2.py3-none-any.whl\nCollecting celery==4.0.* (from -r /vagrant/mangaki//../requirements/./production.txt (line 22))\n  Downloading celery-4.0.2-py2.py3-none-any.whl (396kB)\nCollecting redis==2.10.* (from -r /vagrant/mangaki//../requirements/./production.txt (line 23))\n  Downloading redis-2.10.6-py2.py3-none-any.whl (64kB)\nCollecting Pillow>=4.1 (from -r /vagrant/mangaki//../requirements/./production.txt (line 24))\n  Downloading Pillow-5.0.0-cp34-cp34m-manylinux1_x86_64.whl (5.9MB)\nCollecting dedupe==1.7.* (from -r /vagrant/mangaki//../requirements/./production.txt (line 25))\n  Downloading dedupe-1.7.9.tar.gz (54kB)\nCollecting setuptools-scm==1.15.* (from -r /vagrant/mangaki//../requirements/./production.txt (line 26))\n  Downloading setuptools_scm-1.15.7-py2.py3-none-any.whl\nCollecting django-debug-toolbar==1.8 (from -r /vagrant/mangaki//../requirements/dev.txt (line 3))\n  Downloading django_debug_toolbar-1.8-py2.py3-none-any.whl (205kB)\nCollecting django-extensions (from -r /vagrant/mangaki//../requirements/dev.txt (line 4))\n  Downloading django_extensions-2.0.0-py2.py3-none-any.whl (216kB)\nCollecting django-nose (from -r /vagrant/mangaki//../requirements/dev.txt (line 5))\n  Downloading django_nose-1.4.5-py2.py3-none-any.whl\nCollecting matplotlib (from -r /vagrant/mangaki//../requirements/dev.txt (line 6))\n  Downloading matplotlib-2.1.2-cp34-cp34m-manylinux1_x86_64.whl (15.0MB)\nCollecting flake8 (from -r /vagrant/mangaki//../requirements/dev.txt (line 7))\n  Downloading flake8-3.5.0-py2.py3-none-any.whl (69kB)\nCollecting tensorflow (from -r /vagrant/mangaki//../requirements/dev.txt (line 8))\n  Downloading tensorflow-1.5.0-cp34-cp34m-manylinux1_x86_64.whl (44.4MB)\nCollecting fastFM (from -r /vagrant/mangaki//../requirements/dev.txt (line 9))\n  Downloading fastFM-0.2.11-cp34-cp34m-manylinux1_x86_64.whl (482kB)\nCollecting typing (from -r /vagrant/mangaki//../requirements/dev.txt (line 10))\n  Downloading typing-3.6.4-py3-none-any.whl\nCollecting git-lint (from -r /vagrant/mangaki//../requirements/dev.txt (line 12))\n  Downloading git-lint-0.0.9.tar.gz (41kB)\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n      File \"/tmp/pip-build-i0zu64lq/git-lint/setup.py\", line 29, in <module>\n        long_description=open('README.rst').read(),\n      File \"/home/vagrant/venv/lib/python3.4/encodings/ascii.py\", line 26, in decode\n        return codecs.ascii_decode(input, self.errors)[0]\n    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8309: ordinal not in range(128)\n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-i0zu64lq/git-lint/\n"}
	to retry, use: --limit @/Users/dawars/projects/mangaki/provisioning/site.retry`

**Comment by sk-** [comment]
I think I found the issue. By default open will use a decoder that's platform dependent. See https://docs.python.org/3.6/library/functions.html#open.

Could you try to run setup.py with pull request #108. If that fixes it I will submit it and publish a new version on pypi.

**Comment by Dawars** [comment]
Yes, it works
