### ISSUE TITLE
Install fail for python 3

### ISSUE THREAD

**Issue by w4-jaesup** [sk-/git-lint#112]
``` bash
pip3 install git-lint
```
is trying to install dependency `futures` even for python 3.
Fix would be to remove `futures` from install_requires in `setup.py`

**Comment by OranShuster** [comment]
Not removed but just add the dep as
` extras_require={':python_version == "2.7"': ['futures']}`

**Comment by sk-** [comment]
Thanks for the report and the PR.

It's fixed now. I deployed version 0.1.1 to pypi.
