### ISSUE TITLE
Would it be possible to create a GitHub Action for git-lint?

### ISSUE THREAD

**Issue by cclauss** [sk-/git-lint#139]
https://github.com/features/actions  Actions are usually pretty good fit for linters.

**Comment by sk-** [comment]
It's something I want to explore. What I'm not sure about is whether one can use the Checks API directly from Actions.

In the meantime, check how I'm using git-lint in Travis.

**Comment by sk-** [comment]
Actually this is not possible, as one would need to ship in that action every possible linter available.

What we could do is to create a base github action, with no linter installed that runs git-lint and reports the errors. however, one would need to extend from it to install the linters used in the project.
