### ISSUE TITLE
pylint output format

### ISSUE THREAD

**Issue by itayB** [sk-/git-lint#143]
Hi,

I'm using pylint + Jenkins as part of our CI/CD solution.
Trying to move to git-lint but the output format is different than pylint ouput:
`pylint | tee pylint.out` and `git lint | tee pylint.out` has different output and jenkins plugin can't parse and create report from it.
https://wiki.jenkins.io/display/JENKINS/Violations

Any workaround for this issue? (get the same output / format as in pylint)

**Comment by sk-** [comment]
Hi @itayB, the link you provided specifies that the output must be in XML format, which git lint does not support and won't support, but it seems it also support some other text formats.

git-lint does however, expose the output in a json format which you can later use to build whatever format is supported by Jenkins.
