### ISSUE TITLE
add linters pyflakes, cppcheck, cpplint

### ISSUE THREAD

**Issue by tkruse** [sk-/git-lint#43]
I have tried something similar to git-lint in the past, but had no time to continue on this:
https://github.com/tkruse/unilint
But the code to scape the output from the given tools could be reused.

Also Java linters should include Findbugs

**Comment by sk-** [comment]
@tkruse Feel free to send a PR adding these linters.
Note also that currently you can have your own configuration file called `.gitlint.yaml` at the root of your repo.

I will create separate issues for each linter, so they could be worked on in parallel or different people.

Personally I'm not 100% in favor of adding yet another python linter to the default config. But I'm open to discuss alternatives to generate a default configuration file that you can put in your repo.

Something like `gitlint --generate-config pylint pep8 cpplint rubocop ...`

**Comment by sk-** [comment]
Closing as individual issues were created
