### ISSUE TITLE
Repos with submodules result in fatal errors

### ISSUE THREAD

**Issue by benhutchins** [sk-/git-lint#62]
When updating a submodule reference, git lint throws:

    fatal: no such path 'path/to/module' in HEAD
    Traceback (most recent call last):
      File "/usr/local/bin/git-lint", line 21, in <module>
        sys.exit(gitlint.main(sys.argv))
      File "/Library/Python/2.7/site-packages/gitlint/__init__.py", line 230, in main
        commit=commit)
      File "/Library/Python/2.7/site-packages/gitlint/git.py", line 132, in modified_lines
        ['git', 'blame', '--porcelain', filename]).split(
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['git', 'blame', '--porcelain', u'/absolute/path/to/submodule']' returned non-zero exit status 128

This is because running a `git blame submodule-folder` does not work.

**Comment by benhutchins** [comment]
As my above comment describes the error. The solution is unclear to me. I've for now, just put a try-catch around the subprocess call in `git.py:132`, but I think a better solution would be to check if the path is a registered git module prior to calling a `git blame` on it. You can get the list of submodules easily enough by running `git submodule` which includes the latest hash, or probably more easily would be to load the `.gitmodules` file in the project root directory and parse it (the latter method is much faster as well).

Unless there is a way to do a blame on a submodule, but there is no possible linting benefits so really no point.

**Comment by sk-** [comment]
Thanks for the bug report. I think a better solution would be to pass the option `--ignore-submodules=all` to `git status`.

Over the weekend I'll try it and upload a new version.

**Comment by benhutchins** [comment]
I didn't know about that option. It sounds simplest.
