### ISSUE TITLE
YAML validation seems having trouble to pass syntax `- !rel `

### ISSUE THREAD

**Issue by nirvanaforu** [sk-/git-lint#65]
this is valid syntax though,

city_10_prop_subs_id:
  fields:
    name: subscription_id
    value: 1
  model: tests.jobs.fuel_sdk_proxy_classes:PropertyProxy

legacy_city_10_props:
  fields:
    properties:
      -
        - !rel city_10_prop_subs_id
  model: tests.jobs.fuel_sdk_proxy_classes:RowResultProxy

**Comment by sk-** [comment]
@nirvanaforu Could you please link to where such syntax is defined. I did some quick search on the spec, and I only found that commands starting with `!` are language extensions. What language are you using?

**Comment by sk-** [comment]
Closing as no information was provided in two years.
