### ISSUE TITLE
Make pylint aware of numpy

### ISSUE THREAD

**Issue by sk-** [sk-/git-lint#66]
Add the option `--extension-pkg-whitelist=numpy` to pylint so it is aware of numpy. See https://bitbucket.org/logilab/pylint/issues/397/pylint-and-numpy-produce-e1101-messages

**Comment by addykim** [comment]
Link you provided leads to access denied page. Anywhere else where we can see the same information?

**Comment by sk-** [comment]
https://github.com/PyCQA/pylint/issues/397 has the issue.

One can instead add this to the `pylintrc` file with `extension-pkg-whitelist=numpy`.

I'm closing this issue as it seems that this option is no longer required for `numpy`.
