### ISSUE TITLE
coala

### ISSUE THREAD

**Issue by sils1297** [sk-/git-lint#76]
Hey,

we're currently working on a similar project to yours which however aims not only to wrap around existing linters but also to enable people to create analysis routines. To kickstart our project we're looking into wrapping linters similar to what you do. We have worked very hard in the past years to create a very decent user interaction (editor plugins, interactive CLI, JSON, ...) so it can be used well for production and research usecases and I think it's worth it. Right now I have a prototype of a service ready to test on gitmate.com that uses coala to automatically review GitHub Pull Requests.

Would you be interested in joining forces with us? I think we both could win from that. Let me know if you need anything, you can find some information and links on coala-analyzer.org and I'm totally available for any questions you might have.

**Comment by sils1297** [comment]
see also https://github.com/coala-analyzer/coala/issues/897

**Comment by sk-** [comment]
Hi @sils1297, feel free to reach out to my email. Could you tell me more about what kind of plans you have, advantages of having python bears vs executable bears, how do you plan to normalize the results of several bears/linters (for example many linters already check the spacing but you also have a spacing bear), plans of gitmate (it seems to be like a paid service you want to launch), etc.

**Comment by sils1297** [comment]
sure, just give me your email, write one to me at lasse.schuirmann@gmail.com or join https://gitter.im/coala-analyzer/coala
