### ISSUE TITLE
change PEP8 to pycodestyle

### ISSUE THREAD

**Issue by superzazu** [sk-/git-lint#80]
Hello,

PEP8 linter recently changed its name to pycodestyle :
- discussion: https://github.com/PyCQA/pycodestyle/issues/466
- commit: https://github.com/PyCQA/pycodestyle/commit/26c64badd9ea27cbfbff311f7b3b09b475e80ead

It causes problems when trying to lint python code:

```
SKIPPED: pep8 is not installed. Run pip install pep8.
```

**Comment by hugovk** [comment]
@superzazu @addykim This can be closed, it was changed in the previous commit.

**Comment by Greums** [comment]
Hello,

The fix for this issue has not been merged (PR #84), the issue is still open
